FROM nginx:alpine

# Kopiujemy konfigurację nginx (statyczne pliki będą mountowane przez docker-compose)
# Konfiguracja serwera
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# W obrazie produkcyjnym statyczne pliki kopiujemy, aby nginx mógł je serwować bez wolumenu
COPY static/ /srv/static/

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]