version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Konfiguracja sub-path dla nginx proxy
      - GF_SERVER_ROOT_URL=https://malina.tail384b18.ts.net/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      # Opcjonalne: Disable login dla lokalnego dostępu
      # - GF_AUTH_ANONYMOUS_ENABLED=true
      # - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

volumes:
  grafana-storage:

networks:
  monitoring:
    driver: bridge
