FROM nginx:alpine

# Kopiujemy konfigurację nginx (statyczne pliki będą mountowane przez docker-compose)
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]